version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Setup Ubuntu
          command: bash 00_setup.sh
      - run:
          name: Download Who's on First data
          command: bash 01_download_wof.sh
      - run:
          name: Run full docker-compose process
          command: bash 02_docker_build.sh
      - run:
          name: Run acceptance_tests.sh
          command: bash 03_run_acceptance_tests.sh
