version: 2
jobs:
  build:
    machine: true
    working_directory: /app
    steps:
      - checkout
      - run:
          name: Build and run acceptance tests
          command: sh .circleci/build.sh
